//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeralaPSC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionPaper
    {
        public int QuestionPaperID { get; set; }
        public int ExamID { get; set; }
        public string FilePath { get; set; }
    
        public virtual Exam Exam { get; set; }
    }
}
